### ISSUE TITLE
Portals missing from config file

### ISSUE THREAD

**Issue by sfjuocekr** [FelixReuthlinger/AutoMapPins#29]
Hey, I've used your mod for quite a while and I recently noticed it wasn't adding portals anymore!

So I went into the config, but I could not find anything regarding portal?

I added a section like this, but I probably did not do it correctly:

```
portal:
  categoryConfiguredObjects:
    - TeleportWorld
  name: Portal
  isActive: true
  isPermanent: true
  iconName: portal
```

I've probably added the wrong object under categoryConfiguredObjects?
