### ISSUE TITLE
Pin "portal" blocks TargetPortal mod by Smoothbrain- incompatibility

### ISSUE THREAD

**Issue by arturgaweski** [FelixReuthlinger/AutoMapPins#30]
Hi, since last update where were added portal pins you cannot use popular mod "TargetPortal" by Smoothbrain due to pin blocking portal icon on map. I can't find config for removing portal pins, can you help me a bit? -edit/ i found pin setting for portal, missed it in r2. Anyway it would be better if by default portal pins were deactivated or there should be added in mod page info about pins possibly blocking usage of mods that use map for teleport or other actions.

**Comment by sfjuocekr** [comment]
You should be able to add this:

```
portals:
  categoryConfiguredObjects:
  - portal_stone
  - portal_wood
  isActive: false
  isPermanent: false
  iconName: portal
```

To remove the nearby and permanent portal pins, I think it is just the permanent pins that obscure the clickable pin used by TargetPortal.

I think AMP shouldn't try to draw on those maps shown from other mods, not sure how feasible this is.
